// lib/catalog/archetypes.ts — hand-authored archetype templates for the seeded catalogue.
// Hard constraint: zero React / React Native / Expo imports. Pure TypeScript.

import type { Category, Formality, Season, StyleVector } from '@/lib/types';

export interface Archetype {
  id: string;
  baseName: string;
  brand: string;
  category: Category;
  formality: Formality;
  seasons: Season[];
  description: string;
  /** Partial overrides applied on top of garmentToVector result before clamping. */
  styleHints: Partial<StyleVector>;
  /** Valid keys from COLOR_TO_FAMILY — each becomes one product. */
  colors: string[];
}

// All colour strings below are validated keys of COLOR_TO_FAMILY in lib/types.ts.
// Valid keys: black, white, grey, charcoal, ivory, cream, beige,
//   tan, camel, brown, chocolate, olive, forest, khaki, sage,
//   rust, terracotta, orange, burgundy, mustard,
//   navy, indigo, denim, cobalt,
//   purple, lilac, magenta, pink, red, yellow.

export const ARCHETYPES: Archetype[] = [
  // ---- OUTERWEAR (8 archetypes) ----
  {
    id: 'work-jacket',
    baseName: 'Work Jacket',
    brand: 'Carhartt',
    category: 'outerwear',
    formality: 2,
    seasons: ['fall', 'winter', 'spring'],
    description: 'Classic work jacket in heavyweight canvas with multiple utility pockets.',
    styleHints: { workwear: 0.3, outdoor: 0.2 },
    colors: ['tan', 'brown', 'black', 'olive'],
  },
  {
    id: 'trench',
    baseName: 'Trench Coat',
    brand: 'Burberry',
    category: 'outerwear',
    formality: 4,
    seasons: ['fall', 'spring'],
    description: 'Iconic trench coat with double-breasted front and belted waist.',
    styleHints: { formal: 0.2, vintage: 0.1 },
    colors: ['camel', 'black', 'cream', 'navy'],
  },
  {
    id: 'chore-coat',
    baseName: 'Chore Coat',
    brand: 'A.P.C.',
    category: 'outerwear',
    formality: 2,
    seasons: ['fall', 'spring', 'winter'],
    description: 'French workwear-inspired chore coat with patch chest pockets.',
    styleHints: { workwear: 0.25, vintage: 0.15 },
    colors: ['indigo', 'black', 'olive', 'tan'],
  },
  {
    id: 'technical-shell',
    baseName: 'Technical Shell',
    brand: 'Arc\'teryx',
    category: 'outerwear',
    formality: 2,
    seasons: ['fall', 'winter', 'spring'],
    description: 'Waterproof technical shell with Gore-Tex construction for all-weather performance.',
    styleHints: { outdoor: 0.4, streetwear: 0.1 },
    colors: ['black', 'navy', 'olive', 'grey'],
  },
  {
    id: 'bomber',
    baseName: 'Bomber Jacket',
    brand: 'Alpha Industries',
    category: 'outerwear',
    formality: 2,
    seasons: ['fall', 'spring'],
    description: 'MA-1 style bomber jacket with ribbed cuffs and utility pockets.',
    styleHints: { streetwear: 0.3, vintage: 0.2 },
    colors: ['black', 'olive', 'navy', 'sage'],
  },
  {
    id: 'overshirt',
    baseName: 'Overshirt',
    brand: 'Engineered Garments',
    category: 'outerwear',
    formality: 2,
    seasons: ['fall', 'spring'],
    description: 'Heavyweight flannel overshirt worn as a light layer.',
    styleHints: { outdoor: 0.15, workwear: 0.2, vintage: 0.15 },
    colors: ['rust', 'forest', 'navy', 'tan'],
  },
  {
    id: 'denim-jacket',
    baseName: 'Denim Jacket',
    brand: 'Levi\'s',
    category: 'outerwear',
    formality: 2,
    seasons: ['spring', 'fall'],
    description: 'Classic trucker-style denim jacket with chest flap pockets.',
    styleHints: { vintage: 0.25, streetwear: 0.15 },
    colors: ['denim', 'black', 'indigo', 'grey'],
  },
  {
    id: 'wool-topcoat',
    baseName: 'Wool Topcoat',
    brand: 'Cos',
    category: 'outerwear',
    formality: 4,
    seasons: ['fall', 'winter'],
    description: 'Long single-breasted topcoat in boiled wool with a structured shoulder.',
    styleHints: { formal: 0.3, minimalism: 0.2 },
    colors: ['charcoal', 'camel', 'black', 'grey'],
  },

  // ---- TOP (7 archetypes) ----
  {
    id: 'oxford-shirt',
    baseName: 'Oxford Shirt',
    brand: 'Ralph Lauren',
    category: 'top',
    formality: 3,
    seasons: ['spring', 'summer', 'fall'],
    description: 'Classic Oxford cloth button-down shirt with a relaxed collar.',
    styleHints: { formal: 0.15, workwear: 0.15 },
    colors: ['white', 'cobalt', 'navy', 'pink'],
  },
  {
    id: 'tee',
    baseName: 'Essential Tee',
    brand: 'Uniqlo',
    category: 'top',
    formality: 1,
    seasons: ['spring', 'summer', 'fall'],
    description: 'Supima cotton crew-neck t-shirt with a clean, minimal silhouette.',
    styleHints: { minimalism: 0.3, relaxedFit: 0.1 },
    colors: ['white', 'black', 'grey', 'navy', 'cream'],
  },
  {
    id: 'henley',
    baseName: 'Henley',
    brand: 'James Perse',
    category: 'top',
    formality: 2,
    seasons: ['spring', 'summer', 'fall'],
    description: 'Relaxed henley in slubbed cotton with a three-button placket.',
    styleHints: { relaxedFit: 0.2, minimalism: 0.1 },
    colors: ['white', 'grey', 'charcoal', 'olive'],
  },
  {
    id: 'flannel-shirt',
    baseName: 'Flannel Shirt',
    brand: 'Pendleton',
    category: 'top',
    formality: 2,
    seasons: ['fall', 'winter'],
    description: 'Heavy brushed flannel shirt in a classic plaid pattern.',
    styleHints: { outdoor: 0.2, vintage: 0.2, workwear: 0.1 },
    colors: ['rust', 'forest', 'navy', 'brown'],
  },
  {
    id: 'silk-blouse',
    baseName: 'Silk Blouse',
    brand: 'Vince',
    category: 'top',
    formality: 4,
    seasons: ['spring', 'summer', 'fall'],
    description: 'Fluid silk blouse with a relaxed drape and minimal detailing.',
    styleHints: { formal: 0.2, minimalism: 0.15, colorfulness: 0.1 },
    colors: ['ivory', 'black', 'navy', 'sage'],
  },
  {
    id: 'striped-ls',
    baseName: 'Striped Long-Sleeve',
    brand: 'Saint James',
    category: 'top',
    formality: 2,
    seasons: ['spring', 'fall'],
    description: 'Breton-stripe long-sleeve top in heavyweight cotton jersey.',
    styleHints: { vintage: 0.2, pattern: 0.2, relaxedFit: 0.1 },
    colors: ['navy', 'black', 'tan'],
  },
  {
    id: 'dress-shirt',
    baseName: 'Dress Shirt',
    brand: 'Eton',
    category: 'top',
    formality: 5,
    seasons: ['spring', 'summer', 'fall', 'winter'],
    description: 'Tailored dress shirt in two-ply cotton poplin with a cutaway collar.',
    styleHints: { formal: 0.35, minimalism: 0.15, workwear: 0.1 },
    colors: ['white', 'ivory', 'cobalt', 'charcoal'],
  },

  // ---- BOTTOM (7 archetypes) ----
  {
    id: 'straight-jeans',
    baseName: 'Straight Jeans',
    brand: 'Acne Studios',
    category: 'bottom',
    formality: 2,
    seasons: ['spring', 'fall', 'winter'],
    description: 'Straight-leg jeans in mid-weight selvedge denim with a clean rise.',
    styleHints: { vintage: 0.1, workwear: 0.1 },
    colors: ['denim', 'black', 'indigo', 'grey'],
  },
  {
    id: 'wide-chino',
    baseName: 'Wide-Leg Chino',
    brand: 'Totême',
    category: 'bottom',
    formality: 3,
    seasons: ['spring', 'summer', 'fall'],
    description: 'Wide-leg chino trousers in cotton twill with a pleated front.',
    styleHints: { relaxedFit: 0.2, minimalism: 0.1 },
    colors: ['tan', 'khaki', 'olive', 'cream'],
  },
  {
    id: 'cargo-pant',
    baseName: 'Cargo Pant',
    brand: 'Carhartt WIP',
    category: 'bottom',
    formality: 1,
    seasons: ['spring', 'fall', 'winter'],
    description: 'Relaxed fit cargo trousers with side utility pockets in ripstop cotton.',
    styleHints: { streetwear: 0.2, outdoor: 0.15, workwear: 0.1 },
    colors: ['black', 'olive', 'khaki', 'brown'],
  },
  {
    id: 'wool-trouser',
    baseName: 'Wool Trouser',
    brand: 'Margaret Howell',
    category: 'bottom',
    formality: 4,
    seasons: ['fall', 'winter'],
    description: 'Tailored wool trousers with a slightly high waist and wide leg.',
    styleHints: { formal: 0.25, minimalism: 0.15 },
    colors: ['charcoal', 'navy', 'black', 'grey'],
  },
  {
    id: 'pleated-short',
    baseName: 'Pleated Short',
    brand: 'Ami Paris',
    category: 'bottom',
    formality: 3,
    seasons: ['spring', 'summer'],
    description: 'Pleated chino shorts in a mid-length cut with a clean, tailored finish.',
    styleHints: { minimalism: 0.1, relaxedFit: 0.15 },
    colors: ['tan', 'navy', 'olive', 'cream'],
  },
  {
    id: 'technical-jogger',
    baseName: 'Technical Jogger',
    brand: 'Reigning Champ',
    category: 'bottom',
    formality: 1,
    seasons: ['spring', 'fall', 'winter'],
    description: 'Slim-tapered technical joggers in stretch terry with zippered pockets.',
    styleHints: { streetwear: 0.2, outdoor: 0.1, relaxedFit: 0.15 },
    colors: ['black', 'charcoal', 'navy'],
  },
  {
    id: 'tailored-trouser',
    baseName: 'Tailored Trouser',
    brand: 'Brioni',
    category: 'bottom',
    formality: 5,
    seasons: ['spring', 'summer', 'fall', 'winter'],
    description: 'Handmade suit trousers in Super 150s wool with a full canvas construction.',
    styleHints: { formal: 0.4, minimalism: 0.2 },
    colors: ['charcoal', 'navy', 'black'],
  },

  // ---- FOOTWEAR (7 archetypes) ----
  {
    id: 'leather-boot',
    baseName: 'Leather Boot',
    brand: 'Red Wing',
    category: 'footwear',
    formality: 3,
    seasons: ['fall', 'winter', 'spring'],
    description: 'Classic leather work boot with a Goodyear-welt construction and vibram sole.',
    styleHints: { workwear: 0.25, vintage: 0.2, outdoor: 0.1 },
    colors: ['brown', 'black', 'tan', 'camel'],
  },
  {
    id: 'trail-sneaker',
    baseName: 'Trail Sneaker',
    brand: 'Salomon',
    category: 'footwear',
    formality: 1,
    seasons: ['spring', 'summer', 'fall'],
    description: 'Technical trail runner with aggressive grip outsole and breathable upper.',
    styleHints: { outdoor: 0.35, streetwear: 0.15 },
    colors: ['black', 'olive', 'grey', 'khaki'],
  },
  {
    id: 'minimal-sneaker',
    baseName: 'Minimal Sneaker',
    brand: 'Common Projects',
    category: 'footwear',
    formality: 2,
    seasons: ['spring', 'summer', 'fall'],
    description: 'Clean leather low-top sneaker with tone-on-tone sole and minimal branding.',
    styleHints: { minimalism: 0.3, streetwear: 0.1 },
    colors: ['white', 'black', 'cream', 'tan'],
  },
  {
    id: 'loafer',
    baseName: 'Penny Loafer',
    brand: 'G.H. Bass',
    category: 'footwear',
    formality: 3,
    seasons: ['spring', 'summer', 'fall'],
    description: 'Leather penny loafer with a classic silhouette and hand-sewn vamp.',
    styleHints: { formal: 0.15, vintage: 0.15 },
    colors: ['brown', 'black', 'tan', 'camel'],
  },
  {
    id: 'derby',
    baseName: 'Derby',
    brand: 'Paraboot',
    category: 'footwear',
    formality: 4,
    seasons: ['fall', 'winter', 'spring'],
    description: 'Classic derby in smooth calfskin with a subtle brogue detailing.',
    styleHints: { formal: 0.25, workwear: 0.1 },
    colors: ['black', 'brown', 'camel'],
  },
  {
    id: 'sandal',
    baseName: 'Leather Sandal',
    brand: 'Birkenstock',
    category: 'footwear',
    formality: 1,
    seasons: ['spring', 'summer'],
    description: 'Contoured footbed sandal in oiled nubuck with adjustable buckle straps.',
    styleHints: { relaxedFit: 0.2, outdoor: 0.1 },
    colors: ['tan', 'brown', 'black'],
  },
  {
    id: 'oxford-shoe',
    baseName: 'Oxford Shoe',
    brand: 'Edward Green',
    category: 'footwear',
    formality: 5,
    seasons: ['spring', 'summer', 'fall', 'winter'],
    description: 'Hand-lasted Oxford in Calf Antique leather on a 202 last.',
    styleHints: { formal: 0.4, vintage: 0.15 },
    colors: ['black', 'brown', 'camel'],
  },

  // ---- KNITWEAR (6 archetypes) ----
  {
    id: 'crewneck',
    baseName: 'Crewneck Sweatshirt',
    brand: 'Champion',
    category: 'knitwear',
    formality: 1,
    seasons: ['fall', 'winter', 'spring'],
    description: 'Classic reverse-weave crewneck sweatshirt in heavyweight fleece.',
    styleHints: { relaxedFit: 0.15, streetwear: 0.1 },
    colors: ['grey', 'navy', 'black', 'burgundy'],
  },
  {
    id: 'cardigan',
    baseName: 'Cardigan',
    brand: 'Drake\'s',
    category: 'knitwear',
    formality: 3,
    seasons: ['fall', 'winter', 'spring'],
    description: 'Open-knit wool cardigan with a shawl collar and two patch pockets.',
    styleHints: { vintage: 0.2, relaxedFit: 0.1, formal: 0.1 },
    colors: ['camel', 'grey', 'navy', 'brown'],
  },
  {
    id: 'quarter-zip',
    baseName: 'Quarter-Zip',
    brand: 'Patagonia',
    category: 'knitwear',
    formality: 2,
    seasons: ['fall', 'winter', 'spring'],
    description: 'Polartec fleece quarter-zip pullover with a minimal silhouette.',
    styleHints: { outdoor: 0.2, workwear: 0.1 },
    colors: ['black', 'navy', 'olive', 'grey'],
  },
  {
    id: 'merino-turtleneck',
    baseName: 'Merino Turtleneck',
    brand: 'Everlane',
    category: 'knitwear',
    formality: 3,
    seasons: ['fall', 'winter'],
    description: 'Fine-gauge merino wool turtleneck with a slim roll-neck silhouette.',
    styleHints: { minimalism: 0.2, formal: 0.1 },
    colors: ['ivory', 'black', 'grey', 'camel'],
  },
  {
    id: 'hoodie',
    baseName: 'Pullover Hoodie',
    brand: 'Reigning Champ',
    category: 'knitwear',
    formality: 1,
    seasons: ['fall', 'winter', 'spring'],
    description: 'Midweight terry pullover hoodie with a kangaroo pocket and brushed interior.',
    styleHints: { streetwear: 0.2, relaxedFit: 0.15 },
    colors: ['charcoal', 'black', 'navy', 'olive'],
  },
  {
    id: 'cashmere-sweater',
    baseName: 'Cashmere Sweater',
    brand: 'Loro Piana',
    category: 'knitwear',
    formality: 4,
    seasons: ['fall', 'winter'],
    description: 'Baby cashmere crew-neck sweater with a clean silhouette and reinforced shoulder.',
    styleHints: { formal: 0.15, minimalism: 0.25 },
    colors: ['camel', 'ivory', 'charcoal', 'navy'],
  },

  // ---- ACCESSORY (5 archetypes) ----
  {
    id: 'leather-belt',
    baseName: 'Leather Belt',
    brand: 'Anderson\'s',
    category: 'accessory',
    formality: 3,
    seasons: ['spring', 'summer', 'fall', 'winter'],
    description: 'Woven leather belt in a classic width with a polished box buckle.',
    styleHints: { formal: 0.1, vintage: 0.1 },
    colors: ['brown', 'black', 'tan', 'camel'],
  },
  {
    id: 'wool-scarf',
    baseName: 'Wool Scarf',
    brand: 'Acne Studios',
    category: 'accessory',
    formality: 3,
    seasons: ['fall', 'winter'],
    description: 'Oversized fringed wool scarf in a tonal plaid weave.',
    styleHints: { vintage: 0.1, minimalism: 0.1 },
    colors: ['camel', 'grey', 'black', 'navy'],
  },
  {
    id: 'canvas-cap',
    baseName: 'Canvas Cap',
    brand: 'Corridor',
    category: 'accessory',
    formality: 1,
    seasons: ['spring', 'summer', 'fall'],
    description: 'Six-panel canvas cap with a pre-curved brim and tonal stitching.',
    styleHints: { streetwear: 0.15, outdoor: 0.1 },
    colors: ['tan', 'black', 'olive', 'navy'],
  },
  {
    id: 'tote',
    baseName: 'Canvas Tote',
    brand: 'L.L.Bean',
    category: 'accessory',
    formality: 2,
    seasons: ['spring', 'summer', 'fall', 'winter'],
    description: 'Heavy-duty canvas boat tote with leather handles and reinforced base.',
    styleHints: { workwear: 0.1, outdoor: 0.1 },
    colors: ['tan', 'navy', 'black', 'olive'],
  },
  {
    id: 'silk-pocket-square',
    baseName: 'Silk Pocket Square',
    brand: 'Drakes London',
    category: 'accessory',
    formality: 5,
    seasons: ['spring', 'summer', 'fall', 'winter'],
    description: 'Hand-rolled silk pocket square with a printed paisley motif.',
    styleHints: { formal: 0.3, vintage: 0.2, colorfulness: 0.1 },
    colors: ['navy', 'burgundy', 'forest', 'purple'],
  },
];
